os:
- linux
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- pypy
- pypy3.5
install:
# - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
# - cd $TRAVIS_REPO_SLUG
# - git checkout -qf $TRAVIS_COMMIT
- pip install -r requirements.txt
- pip install .
script:
- pytest --doctest-modules bamnostic/
- pytest

